pipeline {
    agent any

    environment {
        DOCKERHUB_USER = 'suraj960'
        FRONTEND_IMAGE = "suraj960/frontend"
        BACKEND_IMAGE  = "suraj960/backend"
        REGISTRY_CREDS = 'docker-hub-creds'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Push Images') {
            steps {
                script {
                    docker.withRegistry('', "${REGISTRY_CREDS}") {
                        // We point to the specific subfolders for the build context
                        def backend = docker.build("${BACKEND_IMAGE}:${env.BUILD_ID}", "crud-dd-task-mean-app/backend")
                        backend.push()
                        backend.push("latest")

                        def frontend = docker.build("${FRONTEND_IMAGE}:${env.BUILD_ID}", "crud-dd-task-mean-app/frontend")
                        frontend.push()
                        frontend.push("latest")
                    }
                }
            }
        }

        stage('Deploy to VM') {
            steps {
                // This 'dir' block tells Jenkins to run the commands inside the subfolder
                dir('crud-dd-task-mean-app') {
                    sh 'docker compose pull'
                    sh 'docker compose up -d --remove-orphans'
                    sh 'docker image prune -f' 
                }
            }
        }
    }
}
